window.AIO_ALGOLIA_INDEX_ALL = [
  "adobe-dev-console",
  "adobe-io-events",
  "adobe-io-runtime",
  "after-effects",
  "animate",
  "app-builder",
  "audition",
  "bridge",
  "camera-raw",
  "cc-developer-platform-pages",
  "cc-everywhere",
  "cc-libraries-api",
  "cja-apis",
  "commerce-admin-developer",
  "commerce-cloud-tools",
  "commerce-contributor",
  "commerce-extensibility",
  "commerce-frontend-core",
  "commerce-marketplace",
  "commerce-php",
  "commerce-pwa-studio",
  "commerce-testing",
  "commerce-webapi",
  "creative-cloud-libraries",
  "document-services",
  "dreamweaver",
  "experience-platform-apis",
  "fonts",
  "graphql-mesh-gatway",
  "illustrator",
  "indesign",
  "journey-optimizer-apis",
  "lightroom",
  "lightroom-classic",
  "lightroom-public-apis",
  "pdfservices-api-documentation",
  "photoshop",
  "photoshop-api",
  "premiere-pro",
  "stock",
  "stock-api-docs",
  "substance-3d-automation",
  "uxp-photoshop",
  "uxp-photoshop-2021",
  "uxp-xd",
  "xd",
  "xmp-docs",

  /**************************/
  /** Previous Index Names **/
  /**************************/
  "adobeio",
  // "after-effects",
  // "animate",
  // "app-builder",
  // "audition",
  // "bridge",
  // "camera-raw",
  // "cja-apis",
  "cloud-manager",
  // "commerce-admin-developer",
  // "commerce-contributor",
  // "commerce-frontend-core",
  // "commerce-marketplace",
  // "commerce-php",
  // "commerce-pwa-studio",
  // "commerce-webapi",
  "creative-cloud",
  // "document-services",
  // "dreamweaver",
  // "experience-platform-apis",
  // "fonts",
  // "graphql-mesh-gateway",
  // "illustrator",
  // "indesign",
  // "lightroom",
  // "lightroom-classic",
  // "photoshop",
  // "premiere-pro",
  // "stock",
  // "xd",
  "xmp",
];
